---
title: "What Makes Org Mode Hard for PKM"
date: 2023-06-16T13:40:00-04:00
date-modified: ""
categories: 
  - "Personal Knowledge Management"
  - "Building My BASB in Emacs"
draft: false
categories_weight: 4003
series: ["Building My BASB in Emacs - 2023 Capstone Report"]
slug: "what-makes-org-mode-hard-for-pkm"
aliases: 
  - what-makes-org-mode-hard-for-pkm
---

Spoiler alert, it's NOT the parentheses.


## Why BASB in Org is Hard {#why-basb-in-org-is-hard}

The big thing that makes Org Mode difficult for PKM is the same thing that makes it strong: it's flexibility. In particular, the concept of a _single note_ from BASB when translated to Org Mode is... unclear! You could have it be a single file. Or a single headline. Or only some headlines, which you could delineate by property or by tag or by file. And you could blend all these approaches at the same time!

What choice! What decision fatigue!

So, what do you do? What principle do you organize around? Ease of filing? Ease of retrieval? Ease of iteration? Do you even _need_ all these decisions to be made?


## Thinking From Others {#thinking-from-others}

As I was thinking about this, Nick Milo's advice about Maps of Content kept ringing in my ears.

> A Map of Content has to _earn_ its existence. You shouldn't just make one because you think you should.

There are other classic quotes as well. Such as...

> A complex system that works is invariably found to have evolved from a simple system that worked. The inverse proposition also appears to be true: A complex system designed from scratch never works and cannot be made to work. You have to start over, beginning with a working simple system.
>
> -   John Gall

I firmly believe in this in general, but especially for PKM. Most people who get into the discipline are too focused on the tools and not the real output the tools are supposed to enable. I remember looking at a Tana YouTube video on setting up a CRM. The video was a two hours long, and they hadn't put a single entry into the system an hour in. ONLY structure.

Dave Winer [found an analogous problem](http://scripting.com/2017/05/09/rulesForStandardsmakers.html) for naming things in software, because naming things is a big source of wasted energy and effort in software development. His solution is great: always go with the worst name. Translated to PKM: solve any problem with the dumbest, brute force-est, most built-in solution first. Then solve it "correctly" later, _if you need to_. This keeps your focus on producing the valuable stuff that deserves your time and energy, instead of tinkering with things that _feel_ like you're being productive, but in truth are a fancy form of procrastination. Plus the dumber solution, the less mental overhead it takes to make it work, which is good for maintenance.


## My Solution {#my-solution}

So, with the permission to do dumb things first in mind, my suggestion to those thinking about Org mode is to start as simply as possible, which I interpret as starting with **a single org file**, and letting complexity earn itself as things develop.

You'll see this idea, as well as several exceptions I've already made, as I detail the system.
