project:
  type: website

website:
  title: "For the Wynn"
  site-url: https://www.ftwynn.com
  description: "Writing About Things... For the Wynn"
  repo-url: https://github.com/FTWynn/quarto-blog-ftwynn
  repo-actions: [source, issue]
  twitter-card: 
    creator: "@ftwynn"
    site: "@ftwynn"
  open-graph:
    locale: en_US
  navbar:
    right:
      - text: All Posts
        href: /
      - text: Recordings
        href: /#category=Recordings
      - text: Now
        href: /now
      - text: About
        href: /me
        aria-label: "About Me"
      - icon: rss
        href: index.xml
format:
  html:
    theme: 
      - darkly
      - custom.scss
    css: styles.css
    toc: true



