---
slug: "one-of-the-nice-things-about-stoicism"
aliases: 
- /one-of-the-nice-things-about-stoicism
date: 2020-06-01T02:10:32Z
title: "One of the Nice Things About Stoicism"
categories:
- "Philosophy"
---

I've been reading more and more about stoicism lately, and one thing that I really like about it is that you can explain, as well as recall, the basics in about 30 seconds. The four virtues are easy to rattle off, and some of the key lessons boil down to just a couple of phrases (there are some things you can control, and some you can't).
<!--more-->
In addition to being short and easy to remember, those basics also are deep enough that they easily apply to many areas of life, and will take a full lifetime to live up to. 

I've caught myself getting angry more than once this week, only to remember "am I about to choose to live a better life by seeking wisdom, courage, temperance, and justice... or am I heading in a different direction?" If that sentence was any longer, I'm not confident it would have come to mind.