---
slug: "dimension-20-a-crown-of-candy-episode-6-notes"
aliases: 
- /dimension-20-a-crown-of-candy-episode-6-notes
date: 2020-05-19T02:03:40Z
title: "Dimension 20 - A Crown of Candy Episode 6 Notes"
categories:
- "Tabletop Role Playing Games"
---

Spoilers, obviously.

<!--more-->

First, [totally called](https://blog.ftwynn.com/thoughts-on-dropouts-a-crown-of-candy) that player death. I'm _so_ sad it was Lapin, but the lesson is real... DnD after 1am never leads to good things.

That said, there's nothing like a somber quiet among the players to heighten the tension in a tough battle.

Also, a beautiful last moment for him. The tough part going forward will be to not meta-game around the info Lapin got, but it'll be what it'll be.

With a real PK on our hands, now we're _really_ into Game of Thrones territory.

Shame they left Monterrey shackled up. I genuinely wonder what would've happened if they submitted to arrest. Or heck, if they got the pontifax, who would've been pulling the strings then?

I also still think Amethar should have avoided this by claiming he was justifiably nominated by Theo, even if his kingdom is at war. I doubt it would've changed too much, but wasn't that the whole point of re-nominating him?

Anyway, hooray fun DnD games!

## Update with More Thoughts

The thing that I find really striking about this game is that the group is playing Lord of the Rings while Brennan set up Game of Thrones. 

In fact, it goes even a step further. [Harry Potter and the Methods of Rationality](https://www.hpmor.com/) (which if you haven't read, you should!) has a line which I will quote wrongly, noting that many characters don't even understand which story they're in and who the hero is, leading to lots of chaos if we can't get on the same page.

Jet and Ruby think they're in a coming of age story. Amethar thinks he's in a story about the clash of his past and future. Lapin thinks (ahem, _thought_) he was in a story where the Sugar Plum Fairy pulled the strings. 

All of this has led to what in hindsight, as well as readily foresight, seems like unnecessary chaos. The cast even mentions this as they say things like "oh no... I think I would rush her, but oh no..."

Brennan's set up waits for them to rise to the occasion (even though politics is now out as a viable option a bit). I hope they do.