---
slug: "advice-for-new-parents"
aliases: 
- /articles/advice-for-new-parents
date: 2017-12-20T14:24:52Z
date-modified: 2019-12-20
title: "Advice for New Parents"
categories:
- "Parenting"
---

As more and more of my friends hit the age where they seriously debate and then start having kids, I thought I would share what meager advice I've accumulated so far in my first few months of being a father.
<!--more-->
Disclaimer: I am obviously new at this, and reserve the right to change this at any point in time. Some of these I have also gained from others, so I can't take full credit for everything here.

## Advice

### Treat your first kid like it's your second

The tough part about being a parent the first time around is it's new, and all the advice you get in every direction is about being cautious and safe... but if you try to follow everyone's most cautious examples you will absolutely back yourself into a hole. So take some reasonable precautions, but have some faith in the fact that humans have been having kids for generations and most of them turn out fine no matter what you do.

Is your kid rolling over soon enough? Gripping things hard enough? Saying enough proto words? Don't worry. They'll probably all be fine. From a class we took in baby safety:

> "Kids survive in spite of their parents, not because of them."

### Use the hospital nursery if offered

This is your first test for the point above. You might have a romanticized version of what your first night with your baby will be like. You might dread it like an inescapable plague. If your hospital offers a nursery, **USE IT**. The nurse at our hospital mentioned that few first time parents make use of it, but you'll need that rest and you should take advantage of the help if you can.

### Get a night nurse if you can afford it

This is an expensive choice, but there are few times in life where you can genuinely purchase sleep. This is one of them. Even if you're breastfeeding, the ability to have someone else prep everything, bring the baby to you, and then take it away and soothe it if food isn't what it wants is amazing.

*Never underestimate the value of sleep.*

I will also add here the sleep training book that worked for our kid. I bought it solely based on the title, and not only did our night nurse and pediatrician approve, but it delivered on its promise. [Twelve Hours' Sleep by Twelve Weeks Old: A Step-by-Step Plan for Baby Sleep Success by Suzy Giordano](https://www.amazon.com/gp/product/0525949593/ref=as_li_tl?ie=UTF8&tag=fwynn-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=0525949593&linkId=c345eb9c5b0098bcd5257acebf819ee2)

### Babies come in 3 stages: plant > dog > child

I have to give a friend credit for this, but when a kid is young and doesn't do much... it gets to be a real chore. Remembering that this is the plant phase, where you basically water the kid and wait, helps re-frame your mind to not expect too much when they can't really do anything interesting.

That said, plant makes it sound like the kid is a sunflower... when they're really a bit more like [a mandrake](http://harrypotter.wikia.com/wiki/Mandrake). The screaming can be very real.

They graduate from there to dog... running around with a mild sense of reason and understanding basic commands... but not much beyond that.

Then they get language and become a child, asking why about everything and saying I love you and stuff.

I'm currently somewhere between the plant and dog stage, so I'll have to update this post if I have any insights in the later phases.

## Gifts for new parents

Not everyone is a new parent... sometimes they're buying a gift for one. Here are my suggestions that might not be obvious.

### Night Nurse hours

I mentioned this above, and because it's expensive you might not be able to give much, but that's basically sleep you've bought the parents. Is there a greater gift than that?

### Collections of crazy mommy blog/forum posts that turned out fine

This is true for pregnancy as well, but most first time parents will be a little nervous about food safety or material safety at one point or another. Fortunately there are tons of mom blogs and forums where people share stories about things *way worse* than you would expect, and the kids turn out fine. Collecting these (links or full out copies) would be a good gift to help with peace of mind. Bonus points for hitting on issues the parents actively worry about (sprouts, hamburgers, beer, etc.).

### A premium Spotify subscription

I never understood the value of a premium Spotify subscription until my child was peacefully listening to music, only to cry once commercials came on. Fastest $100 dollars I've ever lost.

### Mundane things at 6+ months

Lots of people will gift things for newborns and infants, but few will gift at sizes 6+ months. If you want something practical, clothes or diapers in that size will do the trick.