---
slug: "chromatic-harmonica-first-thoughts"
aliases: 
- /chromatic-harmonica-first-thoughts
date: 2020-08-23T23:35:37Z
title: "Chromatic Harmonica: First Thoughts"
categories:
- "Music"
---

After some significant delays, my chromatic harmonicas were finally deliverd. I figured I would record my first impressions here.
<!--more-->
First, the presence of the thing is very different. I told my wife, the Special 20's were harmonicas, the Swan that came in the mail felt like *an instrument*. It's heavier, plays more notes, and comes in a much bigger case that immediately made me wonder if I should get a different one for carrying it around a convention. A problem for another time.

Second, I do love the deeper notes on the 16 hole harp. I have a feeling I would love bass harmonicas as well if I ever went that route. 

Third, after playing it for a bit, I found myself delighted that Tifa's Theme and Aerith's Theme were both within reasonable reach on first play through. I can tell there will be an even bigger mental break in my brain than on the diatonic, because it was already taking effort to know that two different notes could be on the same hole. With four notes on each hole now, I can feel my brain hurting, which I'm sure will shift with practice. 

I also got my first sense of loss at losing the ability to play Alfyn's theme really well. It'll be a big shift, but there's no longer that terrible bend that plagues me when I get to it.

Fourth, it does really interesting things to my brain to switch back and forth between the harps. I'm going to want to explore that more in the future, but for now I'm planning to stick to chrom for a bit until I get better.

Fifth, a lot of the material out there for learning chrom appears to center around scales. I'm not opposed to this, but it's a little surprising given that there was so little of that in the diatonic world (for obvious reasons I suppose). 

In fact, there isn't a lot of good intro chrom harmonica stuff at all, in my opinion. I picked up [Dave Kettlewell's book](https://www.amazon.com/CHROMATIC-HARMONICA-Techniques-Advice-Worlds-ebook/dp/B013PKI18E/ref=sr_1_1) because I really liked his [YouTube channel](https://www.youtube.com/channel/UCmh-z1ntEUzRae-dFY9VKAg/playlists), and I might extract the useful info later, but it reads like a right brained person dictated into Skype call for an hour and someone typed it up. Not to mention the Kindle formatting is barely legible and the chapters are inaccessible from the sidebar. Dave, among others, recommends [Method for Chromatic Harmonica](https://www.amazon.com/dp/1883217717/ref=rdr_ext_sb_ti_hist_1), so I'll give that a try, as well as peek into Yvonnick Prene's [Harmonica Studio](https://www.harmonicastudio.yvonnickprene.com/). I'll probably post more about this as I go through things.

All in all, it feels uncomfortable to go back to square one, but I already feel like this is the direction I was looking to go, so I'm hopeful about what comes next.