---
slug: "the-power-of-you-are-here"
aliases: 
- /the-power-of-you-are-here
date: 2020-08-06T22:16:51Z
title: "The Power of \"You Are Here\""
categories:
- "Philosophy"
---

One of the things I like about Stoicism is that it encourages thinking up new, shorter, pithier phrases for key ideas. More wisdom per word is the name of the game. For example (not all from Stoic writers):

* What we desire makes us vulnerable
* Ego is the enemy
* What if I had no opinion about this?
* You are the sum of your actions. Choose wisely.

There's one I picked up from a non-Stoic text I'd like to share today: You Are Here.
<!--more-->
I picked up this phrase from the [Designing Your Life](https://www.amazon.com/dp/B01BJSRSEC/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1) book published by the Stanford D-School professors Bill Burnett and Dave Evans. While not trying to be directly philosophical, there are a lot of great implications that run through those three words.

## You are Not Somewhere Else

Whether physically, or in the sense of fate dealing you a different hand, the fact is that at this moment, what you have now is what you have. Wishing you'd been dealt a different hand, whether it's a frustrated spouse, a failing product, or a screaming child, will not change the fact that in this moment, this is what you have.

The only question really worth considering is what will you do from here, with this?

## You Are Not Yet Where You Plan to Be

It is great to have goals, but realizing goals and dreams takes real work. Remembering that we are _here_, and not _there, help crystallize that [real work](https://www.scotthyoung.com/blog/2020/05/04/do-the-real-thing/) is required to reach important goals. As much as we might like to have already crossed the finish line, we'll need to put one foot in front of the other until we've actually done so.

## You Are No Longer Where You've Been Before

It's sometimes all too easy to get caught up in the past. Whether glory-filled better days or cringe-inducing mistakes, thoughts of the past can intrude on the present moment unbidden and all-consuming if not checked. `You Are Here` reminds us, that we are no longer there. No one living has a mistake-free past, and the past, insofar as we know, is unchangeable. 

What will you do next, from here, knowing that?