---
slug: "what-makes-a-good-star-wars-movie"
aliases: 
- /articles/what-makes-a-good-star-wars-movie
date: 2017-12-18T14:24:52Z
date-modified: ""
title: "What Makes A Good Star Wars Movie"
---

As The Last Jedi starts to hit theaters, it seems appropriate for me to write down what makes a good Star Wars movie. My take is a simpler metric than others might consider, completley disregarding plot and character development. It goes like this:
<!--more-->
[A graph, displaying how lightsabers correlate to joy in Star Wars, namely up and to the right](/img/LightsaberGraph.png)

It's that easy. Play Duel of the Fates, turn on a lightsaber (preferably two), and **I AM IN**.

It's worth calling out that by this metric, I judge the prequals as wholly enjoyable movies (for the sum total of the time lightsabers are active). Character development? Plot? Onscreen chemistry? Don't care, don't care, don't care. All I saw was Darth Maul lighting up the second lightsaber, Obi Wan avenging his mentor, Yoda kicking butt, and the Emperor pulling out the red goods. Seriously, I must've watched the fight scenes with Darth Maul *at least* a hundred times.

This is why Episode Seven and Rogue One really missed the mark. No lightsabers. Rogue One has a host of other issues, but this is by far the most important one.

I have hope that the new film will set us back on a more lightsaber-ful path... but we'll have to see.