---
slug: "harmonica-week-01"
aliases: 
- /harmonica-week-01
date: 2020-07-28T16:43:40Z
title: "Harmonica Week 01"
categories:
- "Music"
---

I'm aware that it's dangerous writing too much about stuff that's in progress, but I'm hoping keeping a weekly-ish account of my thoughts will be more instructive than not.

I'm learning the harmonica, in case the title wasn't obvious.
<!--more-->
I'm trying to model this a bit as an [Ultralearning project a la Scott Young](https://www.scotthyoung.com/blog/ultralearning/).  So I figured a good first post would be to outline the framework I'm starting under.

## Goals

* I want to be able to really wail on sad notes in songs that I feel like I can't sing as well anymore
* I want to be able to bust out geek songs at Dragon Con on demand, focusing on this genre as opposed to blues or rock
    * It's not a thing where I'm going for cool, I'm going for remix culture and leaning on the familiar
    * Maybe improvising within those lines, but that's the base
* I want to connect with an artistic expression side of myself that I don't always find easy to connect to
* I want be able to translate any geek song into a harp doable arrangement


## What's the lesson plan?

My Harmonica (Special 20) came with a www.bluesharmonica.com free trial, so I figured I'd start with that. It's for blues, but certainly the basics are probably similar.

To mix with that, I'll pull from harmonicatabs.com to mix in other music I'm interested in.

I'll practice twice a day, 30 minutes scheduled during the day and up to 30 minutes after the kid goes to sleep. Due to space constraints (and to keep my family from throwing things at me), the car will be my concert hall.

We'll re-assess the approach each month, with weekly reviews as we go.

There's also a good checklist I found from some Harmonica YouTube video that gives specifics on what you should be able to do as a competent beginner. 

Namely:

* Can you play a clean, single note on all draw and blow holes?
* Play the harmonica in just the left hand
* Can you play a rhythm pattern for 1 minute without running out of breath?
* Do you know more than 1 melody by heart?
* Can you play a major scale in both directions?
* Can you produce a Hand Wah that is distinct to other listeners? (doesn't have to be perfect)
* Can you sketch out a tab that you understand?

I'd like to try and get there within a month if I can swing it.

# First week results

The first week has gone pretty well I would say. My study song of choice is [Rainbow Connection](https://www.harptabs.com/song.php?ID=699), which I've leaned into way more than the lessons. I'm focused on trying to get clear, single notes and get a little bit of feeling into it. It's been really fun.

I think I need a clearer picture of which mechanics lessons to do each day. I haven't figured out a great way to do the bluesharmonica.com lessons in my car. The phone is fine, and I've printed the sheet music, but it's a little clunky to try and tie it all together. I figured I wouldn't worry too much about it for the first week.

I should probably start recording myself to get a sense of how I sound over time. I should also lean more into formal lessons and using the metronome. I already sense the bending will be a challenge for me (which is where I've stopped in the past), but let's nail all the basics on straight harp first.

I also originally was learning on a C harmonica, but since the lessons were mostly with an A harmonica, I grabbed one of those two and like it a lot better.