---
slug: "thoughts-on-dropouts-a-crown-of-candy"
aliases: 
- /thoughts-on-dropouts-a-crown-of-candy
date: 2020-05-10T20:08:05Z
title: "Thoughts on Dropout's A Crown of Candy"
categories:
- "Tabletop Role Playing Games"
---

So I've been watching [Dimension 20's A Crown of Candy](https://www.youtube.com/watch?v=zOnnqKPh5RY) on [Dropout](https://www.dropout.tv/). At time of writing, five episodes have been published. It's been a real surprise to me how much I'm enjoying it. I thought I would explain why.

**Fair Warning: spoilers through episode 5.**

<!--more-->

I also make a few guesses at some things, and can't wait to see how wrong I was.

## ACoC Has Copious Room for Genuine Plot Turns

Typically in an RPG, even the ones Dimension 20 has done, there's a big arc that everything gravitates to. The Big Bad Evil Guy is out there somewhere, and even if we take on a side quest here or there, there's a sense that eventually we'll have to go deal with that big Dragon / Nightmare / Mastermind that limits how far those turns can go.

In ACoC? not so.

Any of the 7 kingdoms could have any number of plots to be crowned emperor of the land (or maybe to get rid of the system altogether?). Some nations might be better suited to some strategies than others, but at the moment it doesn't look like any one big bad guy is cropping up... and that's amazing. I bet Brennan has thought through how every kingdom is going to play this event for maximum gain. That means who the players choose to ally with and how and when _all matter_, and could significantly change the way the story unfolds.

Which brings me to another piece I'm finding fun...

## Brennan is Playing on the Weaknesses of His PC's

This is not these players' first round of DnD. It's not even their first campaign together as a group. These are professional comedians, trained in improv, and the players clearly thought the entertainment value was going to be their characters.

As such, we got a bumbling king, two comically rebellious daughters, and an aloof kid who's "really more of a seed guy than a war guy."

And then Brennan dropped them in the heart of this mess, and they haven't figured it out _at all_. I don't think they've even started to grasp the shape of the cage they're in. 

This has heightened the suspense so much more than normal, even in typical scenes.

For example, when Ruby and Jet, subbing in for Lapin, head on the clandestine mission with Senator Ciabatta to infiltrate a _fake_ priest's home who has already arrested and from Ciabatta's kingdom... I was holding my breath the entire time. Not because the mission turned out to be deadly. There was one guard Ciabatta dispatched of. But rather, trying to triangulate what the heck is actually going on had me on the edge of my seat the whole time.

* What does Ciabatta really want here? The priest is already captured.
* Why did he ask for help from Candia at all? Ruby and Jet (and certainly Lapin) literally did nothing he couldn't have.
* What was this priest's game with all her blackmail? Was she working alone? Was she working _with_ the church or _against_ it? And if against it, than with who if not her own nation (or at least it's biggest senator)?
* *_Why are you letting Ciabatta take bag loads of black mail to do.... something that's non-specific?_*

And yet... all Ruby and Jet say at the end (because I imagine they're focusing on their characters) is "wow, he was so cool!" Uh huh. And then he magically gets "mistakenly" called out as an emperor candidate the next day, eh? 

In some sense, all the characters are allowed to be this naive, perhaps with the exception of Theo and Lapin. Theo may not be politically enough in the know, but has the right level of distrust. I was hoping to see more double-agent'ing from Lapin with the church, but with a battle in the cathedral next episode, that ship might've sailed.

My point is, they were all so focused on their characters, and on the easy emperor win for Candia, that no one has explored at all what the plans are for the Meatlands, or Veggieland. Breadland,  Dairyland, and the church are clearly in the game right now, but it's still so very early... assuming the PC's wise up to the game they've been dropped into at all.

## In Sum

I'm having a blast this season because it's basically Game of Thrones, the good parts, except easier to tell everyone apart because they're literal food groups instead of all different white guys with beards.

I suspect Brennan might have his first PC death this season if things continue at this rate. 

I'll be watching, and so should you!