---
slug: "dimension-20-a-crown-of-candy-finale-pt"
aliases: 
- /dimension-20-a-crown-of-candy-finale-pt
date: 2020-08-08T22:35:35Z
title: "Dimension 20 - A Crown of Candy - Finale pt. 2"
categories:
- "Tabletop Role Playing Games"
---

Boy, there was some great wrap-up in there, and some disappointment for me as well.
<!--more-->
First, I share Brennan's sentiment in that first moment of the combat for this engagement: He messed up on this homebrew a bit. That whole battle went a bit too smoothly, especially after that nice tee-up on the night before to set up some PvP. Maybe just like in Escape from Bloodkeep, the power of DnD to make friends is just too strong.

That said, big shout out to the dice this round, with absolutely killer story rolls coming up. Payment Day was extremely poetic, Cinnamon was strong, Liam's arc was awesome... and on and on. So in one sense it was very rewarding... but there was no sacrifice, no cost. I'd expected a bit more of a trap card than that given the GoT setting. The big bad NPC's... didn't really do much. So it felt a little steamroll-ish. Unusual for Dimension 20.

I would've liked to see more heroes come back in the finale, as Brennan likes to do. The zoomed out scale seemed to make that tough though. Trade-offs, I suppose.

## Reflecting on the Broader Series

Liam's arc really stands out to me as my favorite. From seed guy, to unwanted war guy, to absolute vengeful badass, to seed guy again... I pretty much enjoyed every bit of that. A big thanks to Ally.

The RP episode before the finale uncovered _a lot_ of story beats that would've been worth exploring in depth. A lot of the D20 shows have amazingly good pacing in this regard, but the end on ACoC felt a bit rushed... only because that episode after the ice cream temple was _so good_. I know I'm a sucker for role play in DnD... but I don't think I was the only one that saw that.

So all in all, I'd say this one was absolutely worth the watch. Great world building, great character development, great arcs all around. A little saccharine at the end, but maybe even that's thematically appropriate ;-)