---
slug: "the-first-bend-reconsidered-i-dont-think-i-want-this"
aliases: 
- /the-first-bend-reconsidered-i-dont-think-i-want-this
date: 2020-08-15T21:57:39Z
title: "The First Bend Reconsidered: I Don't Think I Want This"
categories:
- "Music"
---

So, I know I'm in danger with this current line of thinking, because changing course just as you start learning something can lead to a lot of errant twists without making any progress. I've only just started to learn bending on the harmonica at all, let alone learn to do it well. 

... But I can't get the idea out of my mind that I might want to switch to chromatic harp instead. And while I shouldn't quit before I get a good sense of something, I similarly shouldn't ignore my own feedback and preferences when other viable alternatives exist.

Sure, The grass is always greener on the other side, but there are a few reasons that I'm taking this seriously enough to try a switch.
<!--more-->
## I'm Really Struggling To Enjoy Bending Practice

Though I've heard many players bend and enjoy hearing them play, I'm finding that _I_ simply do not like playing the bends. 

I do not like how they sound when I practice. I do not like how imprecise they are. I do not like how most of the notes on the harp are well defined... only then to have this arbitrary trombone-like component which removes that just to get notes that feel like they should be there already. 

It seems you can still bend notes on the chromatic harmonica, but that style of harp also is much more in line with having a place for all the notes to begin with... no torturing of the instrument necessary. Plus, for my goal (to follow people around at DragonCon and play the themes of any costumes I see), I'll mostly (if not only) be playing melodies anyway.

## The Chromatic Harp Seems Closer to My Goals

With the walk around DragonCon as my goal from the very start, I thought this would be achievable enough on the diatonic. It has enough range, and with the right technique and practice I could pull all the notes out that I needed. Most learning material these days seems to be for diatonic, so there's plenty of help out there. I might have to transpose a few songs into a different key, but no big deal.

However, as I've gotten into it I've learned that diatonic harmonicas tend to be more blues and band focused. This is a pretty far mark outside of what I want to do, and it feels a bit like I'm trying to pit a round peg in a square hole. 

Chromatic's focus on melodies and including accidentals in the design means I carry fewer harps, focus on the stuff that will make people smile, and hopefully won't rely on bends... or at least not as much as on diatonic.

## A Chance to Go Lower

Third, the least impactful factor but not a totally insignificant one, I've found that I love playing lower notes on the harmonica. The 12 and 16 hole chromatics give the full range on those deeper notes without crazy bending work. I'm sure there will be other challenges making the switch, but even just switching the key from a diatonic C harp to a diatonic A harp made practicing much more enjoyable for me. I look forward to even more octave flexibility as I walk down this road.

## Moving Forward

The biggest challenge I think I'll have moving forward is figuring out what new lesson plan I should undertake. Some of the original checklists for beginner intermediate and advanced look like they still apply, but I'll want a lesson plan more focused on chromatics. I'll post here with what I come up with once I've found it.

Hopefully I'm not re-reviewing my harmonica journey too soon, but I think these are probably appropriate adjustments to make 4 weeks in, and I'm trying to be open to the idea that changing course is not the same as failure or abandonment.