---
aliases:
    - dimension-20-neverafter-first-impressions
date: 2023-01-05
description: ""
slug: dimension-20-neverafter-first-impressions
summary:   
title: "Dimension 20 - Neverafter - First Impressions"
categories:
- "Tabletop Role Playing Games"
---

I must admit when I first saw the trailer for this season, I thought "hard pass for me... not into horror." That said, I couldn't avoid seeing a YouTube short about how episode 3 was as crazy as episode 2 of Fantasy High, so I figured I had to give it a shot. At *least* on 2x speed.

So far, I've come to appreciate a few things I didn't expect, and I wanted to jot them down for anyone else that might be on the fence about the series as well.

I'm only up to episode 2, and I'll leave out any real spoilers even then. So expect more posts as the series progresses. Also, sign up for Dropout if you haven't already!

## The Character Twists are Fun

You probably gathered this from the trailer, but the twists on common fairy tales are definitely fun. Ally's take on Mother Goose is really interesting. Shioban's take on Sleeping Beauty is great. The Frog prince turning back into a frog is hilarious. If you like strong twists on classic tales like this, then you're in the right place.

## Gerard is Amazing

To fan boy for a moment, I think Murph playing Gerard is amazing. He's striking a perfect balance between "everything is fine and I don't want to rock the boat" and "I need to go fix things" in a way that I've seen few players do well. He's also a very understated character, which is near and dear to my heart.

## I'm Suprisingly Hooked by the Setting

Perhaps most surprisingly to me, I'm finding the horror element a really compelling setting. Not the body stuff or jump scares, which still isn't for me, but the overarching sense of *dread* and the knife edge that the heroes are walking to try and save the world feels more real now than ever. Even moreso than in Unsleeping City Season 2, which I loved for a similar reason. The Big Bad here is less apathy, but more a sharp hopelessness surrounded by terror. It's... surprising... how much I want to see what happens next.

## One Bummer: Ally Seems to Have Main Character Syndrome *Again*

Ally has done exceptionally well with Mother Goose in not playing the character too hard, but *again* they're the only one holding the world saving item/prophecy. Share the love around the table!